"""Initial schema.

Revision ID: 193bd4ebc398
Revises: 
Create Date: 2020-11-22 13:49:25.955301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193bd4ebc398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bet',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('payment_synced_at', sa.DateTime(), nullable=True),
    sa.Column('won_outcome_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['won_outcome_id'], ['outcome.outcome_id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_table('outcome',
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bet.bet_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_table('bid',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('yes_bid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.outcome_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('yes_contract', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.outcome_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('bid')
    op.drop_table('outcome')
    op.drop_table('bet')
    op.drop_table('user')
    # ### end Alembic commands ###
